server:
  port: 8080
  shutdown: graceful
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,shutdown

  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    root: INFO
    org.example: INFO
    org.springframework: INFO
